name: Build and Release for v1.0.0

on:
  workflow_dispatch:  # This event triggers the workflow manually from the GitHub Actions UI.

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out code at v1.0.0
        uses: actions/checkout@v3
        with:
          ref: 'v1.0.0'  # Hardcoded reference to the tag

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas scipy matplotlib numpy pyinstaller

      - name: Build Executable with PyInstaller
        run: pyinstaller --onefile --windowed ORCASpectrumPlot.py

      - name: Install GitHub CLI
        run: choco install gh

      - name: Upload Binary to Release v1.0.0
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
          gh release upload 'v1.0.0' ./dist/ORCASpectrumPlot.exe --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
