name: Build and Release

on:
  push:
    branches:
      - main  # or the name of your default branch

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # Specify Python 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas scipy matplotlib numpy pyinstaller

    - name: Build Executable with PyInstaller
      run: pyinstaller --onefile --windowed ORCASpectrumPlot.py

    - name: Upload Executable Artifact
      uses: actions/upload-artifact@v2
      with:
        name: ORCASpectrumPlot-Windows
        path: dist/ORCASpectrumPlot.exe
